apiVersion: v2
name: loki
version: 0.1.0
description: Loki for infoset-stg (per-cluster log aggregation)
dependencies:
  - name: loki
    version: 6.16.0
    repository: https://grafana.github.io/helm-charts
