apiVersion: v1
kind: Secret
metadata:
  name: godaddy-credentials
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  api-key: <path:secret/data/argocd#godaddy-api-key>
  api-secret: <path:secret/data/argocd#godaddy-api-secret>
